spring.application.name=demo
server.port=9090
aws.region=ap-south-1

# Enable automatic EC2 start at app startup and stop at app shutdown.
ec2.auto-manage-instance=true
# Replace with your target instance ID.
ec2.managed-instance-id=i-0f3fbbd87a7b73621
